augment_flip: true
augment_rotate: true
dataset_dir: generations/mixed_merge/subproblem_selection_hgs
device: cuda:3
fit_subproblem: true
lr: 0.001
model_save_dir: exps/regression_maml/models
n_batch: 512
n_layers: 6
n_route_neighbors: 10
n_step_save: 5000
train_dir: exps/regression_maml
transformer_heads: 8
